import type { StyleConfig } from './types';

export const DEFAULT_STYLE: StyleConfig = {
  dotType: 'rounded',
  cornerSquareType: 'extra-rounded',
  cornerDotType: 'dot',
  fgMode: 'solid',
  fgColor: '#111827',
  fgColor2: '#4f46e5',
  gradientType: 'linear',
  gradientRotation: 45,
  bgMode: 'solid',
  bgColor: '#ffffff',
  bgColor2: '#eef2ff',
  eyeColorMode: 'same',
  eyeColor: '#4f46e5',
  margin: 40,
  errorCorrection: 'Q',
  logo: null,
  logoSize: 0.28,
  logoMargin: 10,
  hideLogoBgDots: true,
  frameStyle: 'none',
  frameText: 'ESCANÉAME',
  frameColorMode: 'auto',
  frameColor: '#4f46e5',
};

export interface Template {
  id: string;
  name: string;
  emoji: string;
  patch: Partial<StyleConfig>;
}

export const TEMPLATES: Template[] = [
  {
    id: 'clasico',
    name: 'Clásico',
    emoji: '⬛',
    patch: {
      dotType: 'square',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      fgMode: 'solid',
      fgColor: '#0f172a',
      eyeColorMode: 'same',
      frameStyle: 'none',
    },
  },
  {
    id: 'restaurante',
    name: 'Restaurante',
    emoji: '🍽️',
    patch: {
      dotType: 'classy',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      fgMode: 'gradient',
      fgColor: '#f97316',
      fgColor2: '#dc2626',
      gradientType: 'linear',
      gradientRotation: 45,
      eyeColorMode: 'same',
      frameStyle: 'banner',
      frameText: 'MENÚ',
    },
  },
  {
    id: 'cafeteria',
    name: 'Cafetería',
    emoji: '☕',
    patch: {
      dotType: 'classy-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      fgMode: 'gradient',
      fgColor: '#92400e',
      fgColor2: '#d97706',
      frameStyle: 'banner',
      frameText: 'CAFÉ',
    },
  },
  {
    id: 'barberia',
    name: 'Barbería',
    emoji: '💈',
    patch: {
      dotType: 'classy',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      fgMode: 'gradient',
      fgColor: '#111827',
      fgColor2: '#a16207',
      frameStyle: 'outline',
      frameText: 'RESERVA',
    },
  },
  {
    id: 'tienda',
    name: 'Tienda',
    emoji: '🛍️',
    patch: {
      dotType: 'extra-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      fgMode: 'gradient',
      fgColor: '#2563eb',
      fgColor2: '#7c3aed',
      frameStyle: 'banner',
      frameText: 'OFERTAS',
    },
  },
  {
    id: 'hotel',
    name: 'Hotel / WiFi',
    emoji: '🏨',
    patch: {
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      fgMode: 'gradient',
      fgColor: '#0d9488',
      fgColor2: '#0284c7',
      frameStyle: 'banner',
      frameText: 'WIFI GRATIS',
    },
  },
  {
    id: 'gym',
    name: 'Gimnasio',
    emoji: '💪',
    patch: {
      dotType: 'square',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      fgMode: 'gradient',
      fgColor: '#ef4444',
      fgColor2: '#7f1d1d',
      frameStyle: 'banner',
      frameText: 'ÚNETE',
    },
  },
  {
    id: 'boda',
    name: 'Boda / Evento',
    emoji: '💍',
    patch: {
      dotType: 'classy-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      fgMode: 'gradient',
      fgColor: '#ec4899',
      fgColor2: '#8b5cf6',
      gradientType: 'radial',
      frameStyle: 'outline',
      frameText: 'GRACIAS',
    },
  },
  {
    id: 'inmobiliaria',
    name: 'Inmobiliaria',
    emoji: '🏠',
    patch: {
      dotType: 'rounded',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      fgMode: 'solid',
      fgColor: '#1e3a8a',
      eyeColorMode: 'custom',
      eyeColor: '#b45309',
      frameStyle: 'outline',
      frameText: 'MÁS INFO',
    },
  },
  {
    id: 'clinica',
    name: 'Clínica / Citas',
    emoji: '🩺',
    patch: {
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      fgMode: 'gradient',
      fgColor: '#059669',
      fgColor2: '#14b8a6',
      frameStyle: 'banner',
      frameText: 'CITAS',
    },
  },
  {
    id: 'creador',
    name: 'Creador / Redes',
    emoji: '📸',
    patch: {
      dotType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      fgMode: 'gradient',
      fgColor: '#8b5cf6',
      fgColor2: '#ec4899',
      gradientType: 'radial',
      frameStyle: 'banner',
      frameText: 'SÍGUEME',
    },
  },
  {
    id: 'tech',
    name: 'Startup / Tech',
    emoji: '🚀',
    patch: {
      dotType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      fgMode: 'gradient',
      fgColor: '#4f46e5',
      fgColor2: '#06b6d4',
      frameStyle: 'none',
    },
  },
];
